config/routes.rb
Rails.application.routes.draw do

  resources :student_parents
  # resources :messages
  resources :lessons
  resources :courses
  resources :student_attendances
  resources :attendance_descriptions
  resources :student_homeworks
  resources :homeworks
  resources :marks
  resources :roles
  resources :student_subjects
  resources :users
  resources :grades
  resources :marks
  resources :subjects
  resources :students

###### Sessions Log in - Log out // user && studends
  controller :sessions do
		get 'student_login' => :new
		post 'student_login' => :create
		get 'student_logout' => :destroy
		delete 'student_logout' => :destroy

    get 'user_login' => :usernew
    post 'user_login' => :usercreate
    get 'user_logout' => :userdestroy
    delete 'user_logout' => :userdestroy

    get 'parent_login' => :parentnew
    post 'parent_login' => :parentcreate
    get 'parent_logout' => :parentdestroy
    delete 'parent_logout' => :parentdestroy
	end

###### CHARTS
  namespace :charts do
    get 'chart-attendance'
    get 'chart_student_grades'
    get 'chart_user_roles'
    get 'chart_student_marke_grades'
  end

###### Static pages
  namespace :pages do
    get 'home'
    get 'about'
    get 'faqs'
  end

###### Searches
  get 'search' => 'users#search'
  get 'searchAttendance' => 'student_attendances#searchAttendance'

###### Marks and Attendance
  post 'student_attendances/saveAttendance'
  post 'marks/saveMarks'

###### Root "Home"
  root :to => "pages#home"

###### Mailboxer routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

###### Conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authorised

  def new
    @userListMail ||= []

    User.all.each do |user|
      recepient = Receipent.new
      recepient.id = user.id.to_s + ",User"
      recepient.full_name = user.full_name
      recepient.type = "User"
      @userListMail << recepient
    end
    Student.all.each do |student|
      recepient = Receipent.new
      recepient.id = student.id.to_s + ",Student"
      recepient.full_name = student.full_name
      recepient.type = "Student"
      @userListMail << recepient
    end
  end

  def create
    all_recipients = conversation_params[:recipients]
    all_recipients.each do |rec|

      if rec != ""
        rec = rec.split(',')
        if rec[1] == "Student"
          recipients = Student.where(id: rec[0])
          @conversation = @current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
        elsif rec[1] == "User"
          recipients = User.where(id: rec[0])
          @conversation = @current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
        end
      end
    end
    flash[:success] = "Your message was sent!"
    redirect_to conversation_path(@conversation)
  end

  def show
    @receipts = conversation.receipts_for(@current_user)
    conversation.mark_as_read(@current_user)
  end

  def reply
    @current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(@current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(@current_user)
    redirect_to mailbox_inbox_path
  end

  private

  def message_params
    params.require(:message).permit(:body, :subject)
  end

  def conversation_params
    params.require(:conversation).permit(:subject, :body, recipients:[])
  end
end

class Receipent
  attr_accessor :full_name, :id, :type
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://placehold.it/64x64" alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.full_name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <br>
    <%= link_to "view ...", conversation_path(conversation), class: 'btn btn-secondary btn-sm col-sm-2 pull-right'  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <!--% if student_signed_in? %-->
      <!--%= f.select(:recipients, @userListMail.collect {|p| [ p.full_name, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })%-->
      <!--% else %-->
      <%= f.select(:recipients, @userListMail.collect {|p| [ p.full_name, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })%>
      <!--% end %-->
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-secondary btn-lg btn-block" %>
<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img class="media-object" src="http://placehold.it/64x64" alt="...">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.full_name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
    <div class="col-md-6">
      <%= link_to "New Message", new_conversation_path, class: "btn btn-primary btn-md" %>
    </div>
    <div class="col-md-6 text-right">
      <% if conversation.is_trashed?(@current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
      <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Are you sure?'} %>
      <% end %>
    </div>
</div>

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-secondary btn-md col-md-2 pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>