config/routes.rb
Rails.application.routes.draw do

  resources :student_parents
  # resources :messages
  resources :lessons
  resources :courses
  resources :student_attendances
  resources :attendance_descriptions
  resources :student_homeworks
  resources :homeworks
  resources :marks
  resources :roles
  resources :student_subjects
  resources :users
  resources :grades
  resources :marks
  resources :subjects
  resources :students

###### Sessions Log in - Log out // user && studends
  controller :sessions do
		get 'student_login' => :new
		post 'student_login' => :create
		get 'student_logout' => :destroy
		delete 'student_logout' => :destroy

    get 'user_login' => :usernew
    post 'user_login' => :usercreate
    get 'user_logout' => :userdestroy
    delete 'user_logout' => :userdestroy

    get 'parent_login' => :parentnew
    post 'parent_login' => :parentcreate
    get 'parent_logout' => :parentdestroy
    delete 'parent_logout' => :parentdestroy
	end

###### CHARTS
  namespace :charts do
    get 'chart-attendance'
    get 'chart_student_grades'
    get 'chart_user_roles'
    get 'chart_student_marke_grades'
  end

###### Static pages
  namespace :pages do
    get 'home'
    get 'about'
    get 'faqs'
  end

###### Searches
  get 'search' => 'users#search'
  get 'searchAttendance' => 'student_attendances#searchAttendance'

###### Marks and Attendance
  post 'student_attendances/saveAttendance'
  post 'marks/saveMarks'

###### Root "Home"
  root :to => "pages#home"

###### Mailboxer routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

###### Conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/student_parent.rb
class StudentParent < ActiveRecord::Base
  belongs_to :student
  belongs_to :user
end

app/controllers/student_parents_controller.rb
class StudentParentsController < ApplicationController
  before_action :set_student_parent, only: [:show, :edit, :update, :destroy]

  # GET /student_parents
  # GET /student_parents.json
  def index
    @student_parents = StudentParent.all
  end

  # GET /student_parents/1
  # GET /student_parents/1.json
  def show
  end

  # GET /student_parents/new
  def new
    @student_parent = StudentParent.new
    User.all.each do |users|
      @user_role_parent = users.role.to_s == "parent"
    end
  end

  # GET /student_parents/1/edit
  def edit
  end

  # POST /student_parents
  # POST /student_parents.json
  def create
    @student_parent = StudentParent.new(student_parent_params)

    respond_to do |format|
      if @student_parent.save
        format.html { redirect_to @student_parent, notice: 'Student parent was successfully created.' }
        format.json { render :show, status: :created, location: @student_parent }
      else
        format.html { render :new }
        format.json { render json: @student_parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_parents/1
  # PATCH/PUT /student_parents/1.json
  def update
    respond_to do |format|
      if @student_parent.update(student_parent_params)
        format.html { redirect_to @student_parent, notice: 'Student parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_parent }
      else
        format.html { render :edit }
        format.json { render json: @student_parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_parents/1
  # DELETE /student_parents/1.json
  def destroy
    @student_parent.destroy
    respond_to do |format|
      format.html { redirect_to student_parents_url, notice: 'Student parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_parent
      @student_parent = StudentParent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_parent_params
      params.require(:student_parent).permit(:user_id, :student_id)
    end
end

app/helpers/student_parents_helper.rb
module StudentParentsHelper
end

app/views/student_parents/_form.html.erb
<%= render 'shared/errors', object: @student_parent %>

<div class="row">
    <div class="col-xs-12">
        <%= form_for(@student_parent, :html => {class: "form-horizontal", role: "form"}) do |f| %>

        <div class= "form-group">
            <div class="control-label col-sm-2">
                <%= f.label :first_name %>
            </div>
            <div class="col-sm-8">
              <%= f.collection_select :user_id, User.where(:role_id => @user_role_parent), :id, :full_name, {prompt: "Select parent's name"}, class: "form-control chosen-select" %>
            </div>
        </div>

        <div class= "form-group">
            <div class="control-label col-sm-2">
                <%= f.label :first_name %>
            </div>
            <div class="col-sm-8">
              <%= f.collection_select :student_id, Student.all, :id, :full_name, {prompt: "Select student's name"}, class: "form-control chosen-select" %>
            </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-2">
               <%= f.submit class: 'btn btn-primary btn-lg '%>
      	  </div>
          <div class="col-xs-4 col-xs-offset-2">
            <%= link_to 'Go Back ', root_path, class: "btn btn-danger btn-lg pull-right"%>
          </div>
       </div>

        <% end %>
    </div>
</div>

app/views/student_parents/edit.html.erb
<h1>Editing Student Parent</h1>

<%= render 'form' %>

app/views/student_parents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Student Parents</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_parents.each do |student_parent| %>
      <tr>
        <td><%= student_parent.user_id %></td>
        <td><%= student_parent.student_id %></td>
        <td><%= link_to 'Show', student_parent %></td>
        <td><%= link_to 'Edit', edit_student_parent_path(student_parent) %></td>
        <td><%= link_to 'Destroy', student_parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student parent', new_student_parent_path %>

app/views/student_parents/new.html.erb
<h1>New Student Parent</h1>

<%= render 'form' %>

app/views/student_parents/show.html.erb
<div class="row">
  <h3 class = "center">Student's parent</h3>
  <div class="well col-xs-10 col-xs-offset-1 top_margin">
    <div class="caption">
      <h3>Parent name: <%= @student_parent.user.full_name %> </h3>
      <h3>Student name: <%= @student_parent.student.full_name %></h3>
    </div>
    <div class="top_margin">
    <%= link_to 'Viewing', student_parents_path, class: "btn btn-md btn-success glyphicon glyphicon-file" %>
    <%= link_to 'Editing', edit_student_parent_path(@student_parent), class: "btn btn-md btn-primary glyphicon glyphicon-pencil" %>
		<%= link_to 'Delete', student_parent_path(@student_parent), method: :delete, data: {confirm: "Are you sure ? "},
						class: "btn btn-md btn-danger glyphicon glyphicon-trash"%>
    </div>
  </div>
</div>