config/routes.rb
Rails.application.routes.draw do

  resources :student_parents
  # resources :messages
  resources :lessons
  resources :courses
  resources :student_attendances
  resources :attendance_descriptions
  resources :student_homeworks
  resources :homeworks
  resources :marks
  resources :roles
  resources :student_subjects
  resources :users
  resources :grades
  resources :marks
  resources :subjects
  resources :students

###### Sessions Log in - Log out // user && studends
  controller :sessions do
		get 'student_login' => :new
		post 'student_login' => :create
		get 'student_logout' => :destroy
		delete 'student_logout' => :destroy

    get 'user_login' => :usernew
    post 'user_login' => :usercreate
    get 'user_logout' => :userdestroy
    delete 'user_logout' => :userdestroy

    get 'parent_login' => :parentnew
    post 'parent_login' => :parentcreate
    get 'parent_logout' => :parentdestroy
    delete 'parent_logout' => :parentdestroy
	end

###### CHARTS
  namespace :charts do
    get 'chart-attendance'
    get 'chart_student_grades'
    get 'chart_user_roles'
    get 'chart_student_marke_grades'
  end

###### Static pages
  namespace :pages do
    get 'home'
    get 'about'
    get 'faqs'
  end

###### Searches
  get 'search' => 'users#search'
  get 'searchAttendance' => 'student_attendances#searchAttendance'

###### Marks and Attendance
  post 'student_attendances/saveAttendance'
  post 'marks/saveMarks'

###### Root "Home"
  root :to => "pages#home"

###### Mailboxer routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

###### Conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/student_homework.rb
class StudentHomework < ActiveRecord::Base
  belongs_to :Student
  belongs_to :homework
end

app/controllers/student_homeworks_controller.rb
class StudentHomeworksController < ApplicationController
  before_action :set_student_homework, only: [:show, :edit, :update, :destroy]

  # GET /student_homeworks
  # GET /student_homeworks.json
  def index
    @student_homeworks = StudentHomework.all
  end

  # GET /student_homeworks/1
  # GET /student_homeworks/1.json
  def show
  end

  # GET /student_homeworks/new
  def new
    @student_homework = StudentHomework.new
  end

  # GET /student_homeworks/1/edit
  def edit
  end

  # POST /student_homeworks
  # POST /student_homeworks.json
  def create
    @student_homework = StudentHomework.new(student_homework_params)

    respond_to do |format|
      if @student_homework.save
        format.html { redirect_to @student_homework, notice: 'Student homework was successfully created.' }
        format.json { render :show, status: :created, location: @student_homework }
      else
        format.html { render :new }
        format.json { render json: @student_homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_homeworks/1
  # PATCH/PUT /student_homeworks/1.json
  def update
    respond_to do |format|
      if @student_homework.update(student_homework_params)
        format.html { redirect_to @student_homework, notice: 'Student homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_homework }
      else
        format.html { render :edit }
        format.json { render json: @student_homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_homeworks/1
  # DELETE /student_homeworks/1.json
  def destroy
    @student_homework.destroy
    respond_to do |format|
      format.html { redirect_to student_homeworks_url, notice: 'Student homework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_homework
      @student_homework = StudentHomework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_homework_params
      params.require(:student_homework).permit(:student_id, :homework_id)
    end
end

app/helpers/student_homeworks_helper.rb
module StudentHomeworksHelper
end

app/views/student_homeworks/_form.html.erb
<%= form_for(@student_homework) do |f| %>
  <% if @student_homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_homework.errors.count, "error") %> prohibited this student_homework from being saved:</h2>

      <ul>
      <% @student_homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :homework_id %><br>
    <%= f.number_field :homework_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_homeworks/edit.html.erb
<h1>Editing Student Homework</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_homework %> |
<%= link_to 'Back', student_homeworks_path %>

app/views/student_homeworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Student Homeworks</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Homework</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_homeworks.each do |student_homework| %>
      <tr>
        <td><%= student_homework.student_id %></td>
        <td><%= student_homework.homework_id %></td>
        <td><%= link_to 'Show', student_homework %></td>
        <td><%= link_to 'Edit', edit_student_homework_path(student_homework) %></td>
        <td><%= link_to 'Destroy', student_homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student homework', new_student_homework_path %>

app/views/student_homeworks/new.html.erb
<h1>New Student Homework</h1>

<%= render 'form' %>

<%= link_to 'Back', student_homeworks_path %>

app/views/student_homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @student_homework.student_id %>
</p>

<p>
  <strong>Homework:</strong>
  <%= @student_homework.homework_id %>
</p>

<%= link_to 'Edit', edit_student_homework_path(@student_homework) %> |
<%= link_to 'Back', student_homeworks_path %>