config/routes.rb
Rails.application.routes.draw do

  resources :student_parents
  # resources :messages
  resources :lessons
  resources :courses
  resources :student_attendances
  resources :attendance_descriptions
  resources :student_homeworks
  resources :homeworks
  resources :marks
  resources :roles
  resources :student_subjects
  resources :users
  resources :grades
  resources :marks
  resources :subjects
  resources :students

###### Sessions Log in - Log out // user && studends
  controller :sessions do
		get 'student_login' => :new
		post 'student_login' => :create
		get 'student_logout' => :destroy
		delete 'student_logout' => :destroy

    get 'user_login' => :usernew
    post 'user_login' => :usercreate
    get 'user_logout' => :userdestroy
    delete 'user_logout' => :userdestroy

    get 'parent_login' => :parentnew
    post 'parent_login' => :parentcreate
    get 'parent_logout' => :parentdestroy
    delete 'parent_logout' => :parentdestroy
	end

###### CHARTS
  namespace :charts do
    get 'chart-attendance'
    get 'chart_student_grades'
    get 'chart_user_roles'
    get 'chart_student_marke_grades'
  end

###### Static pages
  namespace :pages do
    get 'home'
    get 'about'
    get 'faqs'
  end

###### Searches
  get 'search' => 'users#search'
  get 'searchAttendance' => 'student_attendances#searchAttendance'

###### Marks and Attendance
  post 'student_attendances/saveAttendance'
  post 'marks/saveMarks'

###### Root "Home"
  root :to => "pages#home"

###### Mailboxer routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

###### Conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base

  mount_uploader :lesson_file, LessonFileUploader # to make sure to use the uploader on lesson_file

  belongs_to :subject

  def file_name
  lesson_file.path.split("/").last
  end
  
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    # @subject_select = Subject.find_by(id: params[:to].to_i) if params[:to]
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:lesson_name, :lesson_note, :lesson_file, :subject_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= render 'shared/errors', object: @lesson %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@lesson, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :lesson_name %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :lesson_name, class: "form-control", placeholder: "Lesson Name", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :lesson_note %>
      </div>
      <div class="col-sm-8 col">
        <%= f.text_area :lesson_note, class: "form-control lessonNote", rows: '5', autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :subject_id %>
      </div>
      <div class="col-sm-8">
        <%= f.collection_select :subject_id, Subject.all, :id, :subject_name, {prompt: "select subject"}, {class: "form-control"} %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <!-- <%= f.label :lesson_file %> -->
      </div>
      <div class="col-sm-8"><br>
        <%= f.file_field :lesson_file, class: "form-control-file btn-md" %>
      </div>
    </div><br>
    <div class="from-group">
      <div class="col-xs-offset-2 col-xs-2">
        <%= f.submit class: "btn btn-lg btn-primary" %>
      </div>
      <div class="col-xs-2 col-xs-offset-4">
        <%= link_to 'Go back', root_path, class: 'btn btn-danger btn-lg pull-right' %>
      </div>
    </div>

    <% end %>
  </div>
</div>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th data-field="#" data-sortable="true">ID</th>
      <th data-field="#" data-sortable="true">|</th>
      <th data-field="#" data-sortable="true">Lesson name</th>
      <th data-field="#" data-sortable="true">Lesson note</th>
      <th data-field="#" data-sortable="true">lesson File</th>
      <th data-field="#" data-sortable="true">subject</th>
      <th data-field="#" data-sortable="true">|</th>
      <th data-field="#" data-sortable="true">View</th>
      <th data-field="#" data-sortable="true">Edit</th>
      <th data-field="#" data-sortable="true">Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
    <tr data-link="<%= lessons_path(lesson) %>">
      <td><%= lesson.id %></td>
      <td>|</td>
      <td><%= lesson.lesson_name %></td>
      <td><%= truncate lesson.lesson_note, length: 15 %></td>
      <td><%= link_to lesson.file_name, lesson.lesson_file_url %></td>
      <td><%= lesson.subject.subject_name %></td>
      <td>|</td>
      <td><%= link_to 'view', lesson, class: "btn btn-primary btn-xs glyphicon glyphicon-file" %></td>
      <td><%= link_to 'Edit', edit_lesson_path(lesson), class: "btn btn-primary btn-xs glyphicon glyphicon-pencil" %></td>
      <td><%= link_to 'Delete', lesson, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary btn-xs glyphicon glyphicon-trash" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Home', root_path, class: "btn btn-primary btn-md btn-block glyphicon glyphicon-home" %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form' %>

app/views/lessons/show.html.erb
<div class="row">
  <div class="well col-xs-10 col-xs-offset-1">
    <div class="caption">
      <h3 class = "center"><%= @lesson.lesson_name %></h3>
      <h4>Note:&nbsp;<%= @lesson.lesson_note %></h4><br>
      <h4>Subject:&nbsp;<%= link_to "#{@lesson.subject.subject_name}", subject_path(@lesson.subject), class: "link_style"  %></h4><br>
      <h4>File :<%= link_to @lesson.file_name, @lesson.lesson_file_url, id: "link_file"%></h4><br>
    </div>
    <%= link_to 'Lessons', lessons_path, class: "btn btn-md btn-success glyphicon glyphicon-file" %>
    <%= link_to 'Editing', edit_lesson_path(@lesson), class: "btn btn-md btn-primary glyphicon glyphicon-pencil" %>
		<%= link_to 'Delete', lesson_path(@lesson), method: :delete, data: {confirm: "Are you sure ? "},
						class: "btn btn-md btn-danger glyphicon glyphicon-trash"%>
  </div>
</div>